apiVersion: cloud.google.com/v1
kind: <(Front|Back)end>Config
metadata:
  name: <(front|back)end>-config-default
  namespace: <solution>
spec:
  timeoutSec: <timeout in secs>
  iap:
    enabled: false
    oauthclientCredentials:
      secretName: <item>-secrets
  securityPolicy:
    name: <cluster>-ingress-policy
