apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <component>-pvc
  namespace: <solution>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: <size>
  storageClassName: <storage class>
