services:
  # Application
  app:
    image: app:1.2.3
    ports:
    - "5000:5000"
    environment:
    - dbconnection=mongodb://mongodb:27017
    depends_on:
    - mongodb

  # Sample database service
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db

volumes:
  mongo-data:
