name: 🔖 Assign Assignee & Labels

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: labels-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assignAuthor:
    name: Assign author to PR 🔖
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1.6.2
        with:
          GITHUB_TOKEN: "${{ secrets.R2D2_COMMITTER }}"

  pr-labels:
    name: Assign labels to PR 🔖
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: "${{ secrets.R2D2_COMMITTER }}"
          configuration-path: ".github/pr-labeler.yml"
